config/routes.rb
PresPlom::Application.routes.draw do
  
 
  get "destroy/dashboard"

  
  root :to => 'pages#home'
  
  get 'protected' => 'protected#index'
  get 'sessions/create'
  
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/developer', as: :omniauth

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'  #A tester
  
  resources :users
  

  resources :etudiants

  get 'etudiants/never_connected' => 'etudiants#never_connected', :as => 'never_connected_etudiants'

  resources :materiel_etudiants
  
  resources :materiels
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/'   # dashboard#index 
    resources :users, :etudiants, :materiels, :modele_emails
  end
  
  

end

app/models/materiel.rb
class Materiel < ActiveRecord::Base
  attr_accessible :defaut, :description, :id, :nom, :type_materiel
  
  has_many :materiel_etudiants
  has_many :etudiants, :through => :materiel_etudiants
  accepts_nested_attributes_for :materiel_etudiants
  
 
end

app/controllers/admin/materiels_controller.rb
class Admin::MaterielsController < ApplicationController
  
  def index
    @materiels = Materiel.all
  end
  
  def show
    @materiel = Materiel.find(params[:id])
  end
  
  def new
    @materiel = Materiel.new
  end
  
  def create
    @materiel = Materiel.new
    if @materiel.save 
      redirect_to admin_materiels_path #, :flash => { :success => 'Materiel cree avec succes.' }
    else
      render :action => 'new'
    end
  end
  
  def edit
    @materiel = Materiel.find(params[:id])
  end
  
  def update
    @materiel = Materiel.find(params[:id])
 
    if @materiel.update_attributes(params[:materiel])
      redirect_to admin_materiels_path, :flash => { :success => 'Materiel modifie avec succes.' }
    else
      render :action => 'edit'
    end
  end
  
  def destroy
      Etudiant.find(params[:id]).destroy
      flash[:success] = "Materiel a ete supprime."
      
      redirect_to admin_materiels_path
      
  end
  
end

app/controllers/materiels_controller.rb
class Admin::MaterielsController < ApplicationController
  
  def index
    @materiels = Materiel.all
  end
  
  def show
    
  end
  
  def new
    #@materiel = Materiel.new
  end
  
end

app/helpers/admin/materiel_helper.rb
module Admin::MaterielHelper
end

app/views/admin/materiels/_form.html.erb
<%= form_for([:admin,@materiel]) do |f| %>
<p>
	<%= f.label "Nom :" %>
	<%= f.text_field :nom %>
</p>
<p>
	<%= f.label "Description :" %>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label "Type :" %>
	<%= f.text_field :type_materiel %>
</p>

<p>
	<%= f.label "Par défaut :" %>
	<%= f.check_box :defaut %>
</p>

<p>
	<%= f.submit "Créer le matériel" %>
</p>
<%end%>

app/views/admin/materiels/edit.html.erb
<h1>Editer un matériel</h1>

<%= render 'form' %>

app/views/admin/materiels/index.html.erb
<h1>Matériels</h1>

<table>
  <tr>
    <th>id</th>
    <th>Nom</th>
    <th>Description</th>
    <th>Type</th>
    <th>Par défaut</th>
  </tr>
<% @materiels.each do |materiel| %>
  <tr>
    <td><%= materiel.id %></td>
    <td><%= materiel.nom %></td>
    <td><%= materiel.description  %></td>
    <td><%= materiel.type_materiel %></td>
    <td><%= materiel.defaut %></td>
   
    <td><%= link_to 'Edit', edit_admin_materiel_path(materiel) %></td>
  
  
  </tr>
<% end %>
</table>
 <br /> <%= link_to 'Ajouter un matériel', new_admin_materiel_path %>

 

app/views/admin/materiels/new.html.erb
<h1>Ajouter un matériel</h1>

<%= render 'form' %>

app/views/admin/materiels/show.html.erb
<h1>Matériels disponibles</h1>



<%= @materiel.nom %>