config/routes.rb
PresPlom::Application.routes.draw do
  
 
  get "destroy/dashboard"

  
  root :to => 'pages#home'
  
  get 'protected' => 'protected#index'
  get 'sessions/create'
  
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/developer', as: :omniauth

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'  #A tester
  
  resources :users
  

  resources :etudiants

  get 'etudiants/never_connected' => 'etudiants#never_connected', :as => 'never_connected_etudiants'

  resources :materiel_etudiants
  
  resources :materiels
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/'   # dashboard#index 
    resources :users, :etudiants, :materiels, :modele_emails
  end
  
  

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  
  before_filter :check_authorized
  
  def index
   # if current_user.has_role? :admin
   #   redirect_to '/dashboard#index'
   # else
   #   redirect_to 'http://www.google.com'
   # end
  end
  
  def check_authorized
    redirect_to root_path unless can? :admin, :all
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    #@etudiant = Etudiant.find(params[:id])
  end


  
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<ul>
	<li><%= link_to 'Tous les utilisateurs', admin_users_path %></li>
	<li><%= link_to 'Ajouter un utilisateur', new_admin_user_path %></li>
	<br />
	<li><%= link_to 'Tous les matériels', admin_materiels_path %></li>
	<li><%= link_to 'Ajouter un matériel', new_admin_materiel_path %></li>
	<br />
	<li><%= link_to 'Tous les modèles de mails', admin_modele_emails_path %></li>
	<li><%= link_to 'Ajouter un modèle', new_admin_modele_email_path %></li>
	<br />
	<li><%= link_to 'Mise à jour des diplômants',:controller=>"etudiants", :method => :sync %></li>
</ul>