config/routes.rb
PresPlom::Application.routes.draw do
  
 
  get "destroy/dashboard"

  
  root :to => 'pages#home'
  
  get 'protected' => 'protected#index'
  get 'sessions/create'
  
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/developer', as: :omniauth

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'  #A tester
  
  resources :users
  

  resources :etudiants

  get 'etudiants/never_connected' => 'etudiants#never_connected', :as => 'never_connected_etudiants'

  resources :materiel_etudiants
  
  resources :materiels
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/'   # dashboard#index 
    resources :users, :etudiants, :materiels, :modele_emails
  end
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_superclass   #Etabli la relation d heritage entre User et Etudiant
  
  attr_accessible :uid,
                  :nom, 
                  :prenom, 
                  :idpersonne, 
                  :email, 
                  :departement, 
                  :created_at, 
                  :updated_at, 
                  :as_user_type, 
                  :role_ids
                  
  has_and_belongs_to_many :roles  
  
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  
  #def self.create_with_omniauth(auth)  
  #  create! do |user|  
  #    user.id = auth["id"]  
  #    user.name = auth["user_info"]["name"]  
  #  end  
  #end
  
end
  

app/controllers/admin/users_controller.rb
 class Admin::UsersController < ApplicationController

  before_filter :require_user
  def index
    @users = User.where(as_user_type: 'User').all  # Tous les utilisateurs, exceptés les étudiants
  end
  
  def show
     @user = User.find(params[:id])
  end
  
  def new
     @user = User.new
  end
  
  def create
    @user = User.new(params[:user].merge :as_user_type => 'User') # Création de l'utilisateur, et ajout de la valeur "User" dans l'attribut "as_user_type" 
    #binding.pry
    if @user.save 
      redirect_to admin_users_path #, :flash => { :success => 'Utilisateur cree avec succes.' }
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
 
    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, :flash => { :success => 'Utilisateur modifie avec succes.' }
    else
      render :action => 'edit'
    end
  end
  
  #def destroy
    #User.find(params[:id]).destroy
    #@user.destroy
    #redirect_to admin_users_path, :flash => { :success => 'L\'utilisateur à été correctement effacé.' }
  #end
  
  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      User.find(params[:id]).destroy
      flash[:success] = "User has been deleted."
    end
    redirect_to admin_users_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    #@users = Users.all
  end
  
  def show
    
  end
  
  def new
    #@user = User.new
  end
  
  def create
    #@user = User.new(params[:user])
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin,@user]) do |f| %>
<p>
	<%= f.label :username, "Username :" %>
	<%= f.text_field :uid %>
</p>
<p>
	<%= f.label :nom, "Nom :" %>
	<%= f.text_field :nom %>
</p>
<p>
	<%= f.label :prenom, "Prénom :" %>
	<%= f.text_field :prenom %>
</p>
<p>
	<%= f.label :email, "Email :" %>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :departement, "Département :" %>
	<%= f.select :departement, options_for_select(%w[TIC TIN EC+G HEG FEE Comem+]) %>
</p>

<p>
	<%= f.label :roles, "Rôles :" %>
	<%= f.collection_select(:role_ids, Role.all, :id, :name) %>
</p>

<p>
	<%= f.submit "Créer l\'utilisateur" %>
</p>
<%end%>

app/views/admin/users/edit.html.erb
<h1>Editer un utilisateur</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Utilisateurs:</h1>

<table>
  <tr>
    <th>id</th>
    <th>Username</th>
    <th>Nom</th>
    <th>Prénom</th>
    <th>e-Mail</th>
    <th>Département</th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.uid %></td>
    <td><%= user.nom %></td>
    <td><%= user.prenom %></td>
    <td><%= user.email %></td>
    <td><%= user.departement %></td>
   
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Delete', user, :method => 'delete', :confirm => 'Etes vous sûr ?' %></td>
  </tr>
<% end %>
</table>
 <br /> <%= link_to 'Ajouter un utilisateur', new_admin_user_path %>

 

app/views/admin/users/new.html.erb
<h1>Ajouter un utilisateur</h1>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>Utilisateur</h1>



<%= @user.nom %>