config/routes.rb
PresPlom::Application.routes.draw do
  
 
  get "destroy/dashboard"

  
  root :to => 'pages#home'
  
  get 'protected' => 'protected#index'
  get 'sessions/create'
  
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/developer', as: :omniauth

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'  #A tester
  
  resources :users
  

  resources :etudiants

  get 'etudiants/never_connected' => 'etudiants#never_connected', :as => 'never_connected_etudiants'

  resources :materiel_etudiants
  
  resources :materiels
  
  namespace :admin do 
    get '', to: 'dashboard#index', as: '/'   # dashboard#index 
    resources :users, :etudiants, :materiels, :modele_emails
  end
  
  

end

app/models/materiel_etudiant.rb
class MaterielEtudiant < ActiveRecord::Base
   attr_accessible :quantite, :materiel_id, :etudiant_id
   
   belongs_to :etudiant
   belongs_to :materiel
   
   accepts_nested_attributes_for :etudiant
   accepts_nested_attributes_for :materiel
   
end

app/controllers/materiel_etudiants_controller.rb
class MaterielEtudiantsController < ApplicationController
  # GET /materiel_etudiants
  # GET /materiel_etudiants.json
  def index
    #@materiel_etudiants = MaterielEtudiant.order(materiel_id)
    @materiels = Materiel.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materiel_etudiants }
    end
  end

  # GET /materiel_etudiants/1
  # GET /materiel_etudiants/1.json
  def show
    @materiel_etudiant = MaterielEtudiant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @materiel_etudiant }
    end
  end

  # GET /materiel_etudiants/new
  # GET /materiel_etudiants/new.json
  def new
    
    #materiels.materiel_etudiants.build
    @materiels = Materiel.all
    @materiel_etudiant = MaterielEtudiant.new
    


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @materiel_etudiant }
    end
  end

  # GET /materiel_etudiants/1/edit
  def edit
    @materiel_etudiant = MaterielEtudiant.find(params[:id])
  end

  # POST /materiel_etudiants
  # POST /materiel_etudiants.json
  def create
    @materiel.materiel_etudiants.build(@current_user.as_user_id, quantite: @materiel_etudiant.quantite)
    
    
    #@materiel_etudiant = MaterielEtudiant.new(params[:materiel_etudiant])

    respond_to do |format|
      if @materiel_etudiant.save
        format.html { redirect_to @materiel_etudiant, notice: 'Materiel etudiant was successfully created.' }
        format.json { render json: @materiel_etudiant, status: :created, location: @materiel_etudiant }
      else
        format.html { render action: "new" }
        format.json { render json: @materiel_etudiant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materiel_etudiants/1
  # PUT /materiel_etudiants/1.json
  def update
    @materiel_etudiant = MaterielEtudiant.find(params[:id])

    respond_to do |format|
      if @materiel_etudiant.update_attributes(params[:materiel_etudiant])
        format.html { redirect_to @materiel_etudiant, notice: 'Materiel etudiant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @materiel_etudiant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiel_etudiants/1
  # DELETE /materiel_etudiants/1.json
  def destroy
    @materiel_etudiant = MaterielEtudiant.find(params[:id])
    @materiel_etudiant.destroy

    respond_to do |format|
      format.html { redirect_to materiel_etudiants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/materiel_etudiants_helper.rb
module MaterielEtudiantsHelper
end

app/views/materiel_etudiants/_form.html.erb
<table>
  <tr>
    <th>Nom</th>
    <th>Description</th>
    <th>Type</th>
    <th>Quantité souhaitée</th>
  </tr>
<% @materiels.each do |materiel| %>
  <tr>
    <td><%= materiel.nom %></td>
    <td><%= materiel.description  %></td>
    <td><%= materiel.type_materiel %></td>
    <td><%= materiel_etudiant.quantite %></td>
   
  
  </tr>
<% end %>
</table>
<p>
	<%= f.submit "Valider la commande" %>
</p>

app/views/materiel_etudiants/edit.html.erb
<h1>Editing materiel_etudiant</h1>

<%= render 'form' %>

<%= link_to 'Show', @materiel_etudiant %> |
<%= link_to 'Back', materiel_etudiants_path %>

app/views/materiel_etudiants/index.html.erb
<h1>Listing materiel_etudiants</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materiel_etudiants.each do |materiel_etudiant| %>
  <tr>
    <td><%= link_to 'Show', materiel_etudiant %></td>
    <td><%= link_to 'Edit', edit_materiel_etudiant_path(materiel_etudiant) %></td>
    <td><%= link_to 'Destroy', materiel_etudiant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Materiel etudiant', new_materiel_etudiant_path %>

app/views/materiel_etudiants/new.html.erb
<h1>Votre choix de matériel</h1>

<%= render 'form' %>

<%= link_to 'Back', materiel_etudiants_path %>

app/views/materiel_etudiants/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_materiel_etudiant_path(@materiel_etudiant) %> |
<%= link_to 'Back', materiel_etudiants_path %>